### ISSUE TITLE
Tagging exists in the content for comments

### ISSUE THREAD

**Issue by bwentwor** [ibm-cloud-docs/AvailabilityMonitoring#1]
On the "About Availability Monitoring" page, you see HTML tagging to indicate the information is being commented out. This information should not show on the published site. Is some information showing on the page for a future release? See the following screen shot:
![screen shot 2018-10-04 at 9 02 38 am](https://user-images.githubusercontent.com/15213938/46479385-8a1d0b00-c7b4-11e8-88e0-84e2273ba9e3.png)

**Comment by bwentwor** [comment]
@rairosul FYI - A fix is probably needed.

**Comment by reka94** [comment]
Closing this issue due to the removal of the product.
