### ISSUE TITLE
There are no links for the 'Video Tutorial Library '  or 'Welcome to Monitoring' ?

### ISSUE THREAD

**Issue by mwilcox12015** [ibm-cloud-docs/AvailabilityMonitoring#2]
Regarding: 

    Video tutorial library - The Video tutorial library contains videos on how to create Bluemix applications, create Availability Monitoring tests, create test scripts with Selenium IDE, and send alerts to Slack.
    Welcome to Monitoring! - The Welcome to Monitoring guide highlights areas of the dashboard and explains each feature of Availability Monitoring.
To open a guide, click the Help icon Help icon; then, click the guide that you want to view.

For Firefox there are no links or information icons to click on ?

**Comment by reka94** [comment]
Closing this issue due to the removal of the product.
