### ISSUE TITLE
Alert notification link not working

### ISSUE THREAD

**Issue by abhiraj-mehrotra** [ibm-cloud-docs/AvailabilityMonitoring#3]
On https://cloud.ibm.com/docs/services/AvailabilityMonitoring?topic=availability-monitoring-avmon_notifications

When user clicks on Alert notification, user gets redirected to a non existing page.

![image](https://user-images.githubusercontent.com/686589/66544199-1a72f600-eb55-11e9-8669-ed2e4fa6702e.png)

![image](https://user-images.githubusercontent.com/686589/66544224-2959a880-eb55-11e9-95e7-32a059d4762a.png)

**Comment by reka94** [comment]
Closing this issue due to the removal of the product.
